A matrix is represented in rows and columns. If a det of matrix is 0 the n matrix is called singular matrix and if not then it called non singular matrix.

A matrix that is close to being singular i.e determinant is close to zero is called ill-conditioned.

In [ ]:
import numpy as np
A = [1,2]
B = [2,3]
c = np.concatenate((A,B))
c

array([1, 2, 2, 3])

In [ ]:
a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]
A = np.abs(a)

diag = np.diag(A)

off_diag = np.sum(A, axis=1)-diag

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('not diagonally dominant')

matrix is diagonally dominant


In [ ]:
epsilon = 0.001

x_old = np.zeros(3) # Initial guess for the solution vector [x0, x1, x2]

for i in range(1,51):

    x_new = x_old.copy()

    # Calculate new values for x1, x2, x3 using the values from x_old (previous iteration)
    x_new[0] = (14 - 3*x_old[1] + 3*x_old[2]) / 8

    x_new[1] = (5 + 2*x_new[0] - 5*x_old[2]) / (-8)

    x_new[2] = (-8 - 3*x_new[0] - 5*x_new[1]) / (-5)

    if np.all(np.abs(x_new-x_old) < epsilon):
      print(f'converged at iteration {i}')
      break

    x_old = x_new.copy()

    print(f'Iteration {i} : {x_new[0]:.6f} {x_new[1]:.6f} {x_new[2]:.6f}')


Iteration 1 : 1.750000 -1.062500 1.587500
Iteration 2 : 2.743750 -0.318750 2.927500
Iteration 3 : 2.967344 0.462852 3.843258
Iteration 4 : 3.017652 1.022623 4.433214
Iteration 5 : 3.028972 1.388516 4.805899
Iteration 6 : 3.031519 1.620807 5.039718
Iteration 7 : 3.032092 1.766801 5.186056
Iteration 8 : 3.032221 1.858230 5.277562
Iteration 9 : 3.032250 1.915414 5.334764
Iteration 10 : 3.032256 1.951163 5.370517
Iteration 11 : 3.032258 1.973509 5.392863
Iteration 12 : 3.032258 1.987475 5.406830
Iteration 13 : 3.032258 1.996204 5.415559
Iteration 14 : 3.032258 2.001660 5.421015
Iteration 15 : 3.032258 2.005070 5.424425
Iteration 16 : 3.032258 2.007201 5.426556
Iteration 17 : 3.032258 2.008533 5.427888
converged at iteration 18


In [ ]:
# solution of matrix using numpy

A = np.array([[4, 3, -5], [-2, -4, 5], [8, 8, 0]])
B = np.array([2, 5, -3])

x = np.linalg.solve(A, B)

A_inv = np.linalg.inv(A)


array([[ 0.33333333,  0.33333333,  0.04166667],
       [-0.33333333, -0.33333333,  0.08333333],
       [-0.13333333,  0.06666667,  0.08333333]])

In [ ]:
import numpy as np

def my_is_orthogonal(v1,v2,tol):

  A1 = np.linalg.norm(v1)
  A2 = np.linalg.norm(v2)

  # Handle cases where one or both vectors might be zero vectors
  if A1 == 0 or A2 == 0:
    return 1 # Zero vector is considered orthogonal to all vectors

  # Use np.dot for 1D arrays to get scalar dot product
  dot_product = np.dot(v1,v2)

  # To prevent floating point errors causing values slightly outside [-1, 1] for arccos
  cosine_theta = np.clip(dot_product/(A1*A2), -1.0, 1.0)
  theta = np.arccos(cosine_theta)

  # Check for orthogonality (angle close to pi/2)
  if np.abs(theta - np.pi/2) < tol:
    return 1
  else:
    return 0

#Call .flatten() on the numpy array object
v1 = np.array([[1],[0.001]]).flatten()
v2 = np.array([[0.001], [1]]).flatten()

print(my_is_orthogonal(v1, v2, 0.01))
print(v1, v2)

1
[1.    0.001] [0.001 1.   ]


In [9]:
import numpy as np

def my_make_ind(A):

  n = np.linalg.matrix_rank(A) # rank of a matrix
  B = []

  for j in range(A.shape[1]):

    #checking column one by one
    col = A[:, j:j+1]

    if len(B)==0:
      B.append(col)

    else:
      #test for independent column
      column_stack = np.hstack([np.hstack(B), col])

      rank_column_stack = np.linalg.matrix_rank(column_stack)

      if rank_column_stack > len(B):
        B.append(col)

    if len(B)==n:
      break
  return np.hstack(B)

A = np.array([[12,24,0,11,-24,18,15],
              [19,38,0,10,-31,25,9],
              [1,2,0,21,-5,3,20],
              [6,12,0,13,-10,8,5],
              [22,44,0,2,-12,17,23]])

B = my_make_ind(A)
print(len(B))
print("Rank of B:", np.linalg.matrix_rank(B))

5
Rank of B: 4


In [30]:
# code to find out matrix is square or not
def sqr_matrix(A):
  num_rows = len(A)

  for row in A:
    num_column = len(row)
    if num_column != num_rows:
      return None
    else: return A

A = [[1,2],
     [3,4]]

B = [[1,2,3], [4,5,6]]

print(sqr_matrix(A))
print(sqr_matrix(B))

[[1, 2], [3, 4]]
None


In [57]:
# creating minor of a matrix using numpy

def create_minor(matrix, row, col):
    """Remove specified row and column."""
    del_row = np.delete(matrix, row, axis=0)
    del_column = np.delete(del_row, col, axis=1 )
    minor = del_column
    return minor

A = np.array([[1,2, 3], [3, 4, 5], [5, 6, 7]])
print(create_minor(A, 0, 0))

[[4 5]
 [6 7]]


In [81]:
# minor of a matrix without using numpy
def minor(matrix, row, col):
   for i in matrix.shape[0]:
    for j in matrix.shape[1]:
      if i != row and j!= col:
        minor = np.array([[matrix[i][j]]])
    return minor

minor = np.array([[1,0, 3], [0, 4, 5], [0, 6, -5]])

for row in range(minor.shape[0]):
    for col in range(minor.shape[1]):
         print(f'M[{row}][{col}]:\n',create_minor(minor, row, col))

M[0][0]:
 [[ 4  5]
 [ 6 -5]]
M[0][1]:
 [[ 0  5]
 [ 0 -5]]
M[0][2]:
 [[0 4]
 [0 6]]
M[1][0]:
 [[ 0  3]
 [ 6 -5]]
M[1][1]:
 [[ 1  3]
 [ 0 -5]]
M[1][2]:
 [[1 0]
 [0 6]]
M[2][0]:
 [[0 3]
 [4 5]]
M[2][1]:
 [[1 3]
 [0 5]]
M[2][2]:
 [[1 0]
 [0 4]]


In [79]:
# defining the determinant of a matrix using recurssion relation

def my_rec_det(M):

# checking for square matrix
   if M.shape[0] != M.shape[1]:
      return None

# the determinant of 2d square matrix
   elif M.shape[0] == 2:
      det_m = M[0][0]*M[1][1] - M[1][0]*M[0][1]
      return det_m

# determinant of nd squate matrix
   else:
       det = 0
       for j in range(M.shape[1]):
           minor = create_minor(M,0,j)
           get_det = (-1)**j * M[0][j]*my_rec_det(minor)
           det += get_det
       return det

M = np.array([[1, 2, 11], [-5, 1, 10], [3, 9, 1]])
A = np.array([[1,2], [-5,4]])
B = np.array([[1, 0, -5, -8], [2, 7, 0, 1], [1, -2, 0, -4], [1, 8, 4, 0]])
mat = np.array([[1,2,-9], [3, 0 ,-7]])
print(my_rec_det(M))
print(my_rec_det(A))
print(my_rec_det(B))
print(my_rec_det(mat))


-547
14
-478
None


In [115]:
from sympy import symbols, Poly

def f(x):
  return x**2+2

def df(x):
  return 2*x

def coeff_vec(p, dp):
  x = symbols('x')

  exp = p(x)
  dexp = dp(x)

  p = Poly(exp,x).all_coeffs()
  D = Poly(dexp,x).all_coeffs()
  return p, D



print(coeff_vec(f, df))

([1, 0, 2], [2, 0])


In [41]:
# finding largest matrix

import numpy as np

x = np.array([1, 1])
a = np.array([[0, 2], [2, 3]])

tol = 0.01
max_iter = 100

old_eigenval = 0

for i in range(max_iter+1):
  y = np.dot(a,x)

  eigenval = abs(y).max()
  eigenvec = y/eigenval

  if np.abs(eigenval-old_eigenval) < tol:
    break

  x = eigenvec
  old_eigenval = eigenval


  print(f'Iterations: {i+1}')
  print(f'Eigenvalue: {eigenval}')
  print(f'Eigenvector: {eigenvec}')

print(f'eigenvale and eigenvector converged after {i} iteration')

Iterations: 1
Eigenvalue: 5
Eigenvector: [0.4 1. ]
Iterations: 2
Eigenvalue: 3.8
Eigenvector: [0.52631579 1.        ]
Iterations: 3
Eigenvalue: 4.052631578947368
Eigenvector: [0.49350649 1.        ]
Iterations: 4
Eigenvalue: 3.987012987012987
Eigenvector: [0.50162866 1.        ]
Iterations: 5
Eigenvalue: 4.0032573289902285
Eigenvector: [0.49959317 1.        ]
eigenvale and eigenvector converged after 5 iteration


In [52]:
# finding smallest eigenvalue

import numpy as np

x = np.array([1, 1])
a = np.array([[0, 2], [2, 3]])

a_inv = np.linalg.inv(a)

tol = 0.01
max_iter = 100

old_eigenval = 0

for i in range(max_iter):
  y = np.dot(a_inv,x)

  eigenval = abs(y).max()
  eigenvec = y/eigenval

  if np.abs(eigenval-old_eigenval) < tol:
    break

  x = eigenvec
  old_eigenval = eigenval


  print(f'Iterations: {i+1}')
  print(f'Eigenvalue: {eigenval}')
  print(f'Eigenvector: {eigenvec}')

print(f'eigenvale and eigenvector converged after {i} iteration')

Iterations: 1
Eigenvalue: 0.5
Eigenvector: [-0.5  1. ]
Iterations: 2
Eigenvalue: 0.875
Eigenvector: [ 1.         -0.28571429]
Iterations: 3
Eigenvalue: 0.8928571428571428
Eigenvector: [-1.    0.56]
Iterations: 4
Eigenvalue: 1.03
Eigenvector: [ 1.         -0.48543689]
Iterations: 5
Eigenvalue: 0.9927184466019418
Eigenvector: [-1.          0.50366748]
eigenvale and eigenvector converged after 5 iteration


In [55]:
# finding eigenvalue and eigenvector using numpy

a = np.array([[0, 2], [2, 3]])

B = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])

eigenval, eigenvec = np.linalg.eig(B)

print(eigenval, eigenvec)

[ 8.80916362  0.92620912 -0.73537273] [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
